'use client'
import Header from '@/ui/components/layout/header/Header'
import Footer from '@/ui/components/layout/footer/Footer'
import type { Metadata } from 'next'
// import StyledComponentsRegistry from '@/libs/styledRegistry'
import Main from '@/ui/components/layout/Main'
// import styles from './page.module.scss';
import '../ui/globals.scss'
import styles from './layout.module.scss'
// import GlobalStyle from '@/components/Globaltyle';
// import { AuthProvider } from '@/Provider'
import StyledComponentsRegistry from '@/lib/helpers/styledRegistry'
import { Open_Sans, Roboto } from 'next/font/google'
import { usePathname } from 'next/navigation'
import { AuthProvider } from '@/context/AuthContext'

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
})
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()
  const isAdmin = pathname.startsWith('/admin')
  const isInstructor = pathname.startsWith('/instructor')
  const isStudent = pathname.startsWith('/student')
  return (
    <html lang='en'>
      <body>
        <StyledComponentsRegistry>
          <AuthProvider>
            <div className={styles.wrappe}>
              {!isAdmin || !isInstructor || (!isStudent && <Header />)}
              <Main>{children}</Main>
              {!isAdmin || !isInstructor || (!isStudent && <Footer />)}
            </div>
          </AuthProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
