'use client'
import type { Metadata } from 'next'
import '../ui/globals.scss'
import StyledComponentsRegistry from '@/lib/helpers/styledRegistry'
import { Open_Sans, Roboto } from 'next/font/google'
import { AuthProvider } from '@/context/AuthContext'
import styled from 'styled-components'
import { Suspense, useState } from 'react'
import mq from '@/lib/utilities/mediaQueries'
import boxProperty from '@/lib/utilities/boxProperty'
import Themes from '@/lib/utilities/themes'
import Main from '@/ui/components/layout/Main'

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <StyledComponentsRegistry>
          <AuthProvider>
            <Suspense fallback={null}>
              <Container>
                <Main>{children}</Main>
              </Container>
            </Suspense>
          </AuthProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Container = styled.div`
  ${mq('mobileS')(`
  
    ${boxProperty('100%', '100%', 'auto', '0px', Themes.$black)};
    // background:${Themes.$special};
  `)}

  ${mq('tablet')(`
    // grid-template-rows: 80px auto 400px;
  `)}

  ${mq('laptop')(`
  `)}

  ${mq('laptopL')(`

  `)}
`
