
const countries = [
  { name: 'Andorra', code: 'AD', dialCode: '+376' },
  { name: 'United Arab Emirates', code: 'AE', dialCode: '+971' },
  { name: 'Afghanistan', code: 'AF', dialCode: '+93' },
  { name: 'Antigua and Barbuda', code: 'AG', dialCode: '+1-268' },
  { name: 'Anguilla', code: 'AI', dialCode: '+1-264' },
  { name: 'Albania', code: 'AL', dialCode: '+355' },
  { name: 'Armenia', code: 'AM', dialCode: '+374' },
  { name: 'Angola', code: 'AO', dialCode: '+244' },
  { name: 'Argentina', code: 'AR', dialCode: '+54' },
  { name: 'American Samoa', code: 'AS', dialCode: '+1-684' },
  { name: 'Austria', code: 'AT', dialCode: '+43' },
  { name: 'Australia', code: 'AU', dialCode: '+61' },
  { name: 'Aruba', code: 'AW', dialCode: '+297' },
  { name: 'Aland Islands', code: 'AX', dialCode: '+358' },
  { name: 'Azerbaijan', code: 'AZ', dialCode: '+994' },
  { name: 'Bosnia and Herzegovina', code: 'BA', dialCode: '+387' },
  { name: 'Barbados', code: 'BB', dialCode: '+1-246' },
  { name: 'Bangladesh', code: 'BD', dialCode: '+880' },
  { name: 'Belgium', code: 'BE', dialCode: '+32' },
  { name: 'Burkina Faso', code: 'BF', dialCode: '+226' },
  { name: 'Bulgaria', code: 'BG', dialCode: '+359' },
  { name: 'Bahrain', code: 'BH', dialCode: '+973' },
  { name: 'Burundi', code: 'BI', dialCode: '+257' },
  { name: 'Benin', code: 'BJ', dialCode: '+229' },
  { name: 'Saint Barthelemy', code: 'BL', dialCode: '+590' },
  { name: 'Bermuda', code: 'BM', dialCode: '+1-441' },
  { name: 'Brunei', code: 'BN', dialCode: '+673' },
  { name: 'Bolivia', code: 'BO', dialCode: '+591' },
  { name: 'Bonaire', code: 'BQ', dialCode: '+599' },
  { name: 'Brazil', code: 'BR', dialCode: '+55' },
  { name: 'Bahamas', code: 'BS', dialCode: '+1-242' },
  { name: 'Bhutan', code: 'BT', dialCode: '+975' },
  { name: 'Bouvet Island', code: 'BV', dialCode: '+47' },
  { name: 'Botswana', code: 'BW', dialCode: '+267' },
  { name: 'Belarus', code: 'BY', dialCode: '+375' },
  { name: 'Belize', code: 'BZ', dialCode: '+501' },
  { name: 'Canada', code: 'CA', dialCode: '+1' },
  { name: 'Cocos (Keeling) Islands', code: 'CC', dialCode: '+61' },
  { name: 'Democratic Republic of the Congo', code: 'CD', dialCode: '+243' },
  { name: 'Central African Republic', code: 'CF', dialCode: '+236' },
  { name: 'Republic of the Congo', code: 'CG', dialCode: '+242' },
  { name: 'Switzerland', code: 'CH', dialCode: '+41' },
  { name: 'Ivory Coast', code: 'CI', dialCode: '+225' },
  { name: 'Cook Islands', code: 'CK', dialCode: '+682' },
  { name: 'Chile', code: 'CL', dialCode: '+56' },
  { name: 'Cameroon', code: 'CM', dialCode: '+237' },
  { name: 'China', code: 'CN', dialCode: '+86' },
  { name: 'Colombia', code: 'CO', dialCode: '+57' },
  { name: 'Costa Rica', code: 'CR', dialCode: '+506' },
  { name: 'Cuba', code: 'CU', dialCode: '+53' },
  { name: 'Cape Verde', code: 'CV', dialCode: '+238' },
  { name: 'Curacao', code: 'CW', dialCode: '+599' },
  { name: 'Christmas Island', code: 'CX', dialCode: '+61' },
  { name: 'Cyprus', code: 'CY', dialCode: '+357' },
  { name: 'Czech Republic', code: 'CZ', dialCode: '+420' },
  { name: 'Germany', code: 'DE', dialCode: '+49' },
  { name: 'Djibouti', code: 'DJ', dialCode: '+253' },
  { name: 'Denmark', code: 'DK', dialCode: '+45' },
  { name: 'Dominica', code: 'DM', dialCode: '+1-767' },
  { name: 'Dominican Republic', code: 'DO', dialCode: '+1-809' },
  { name: 'Algeria', code: 'DZ', dialCode: '+213' },
  { name: 'Ecuador', code: 'EC', dialCode: '+593' },
  { name: 'Estonia', code: 'EE', dialCode: '+372' },
  { name: 'Egypt', code: 'EG', dialCode: '+20' },
  { name: 'Western Sahara', code: 'EH', dialCode: '+212' },
  { name: 'Eritrea', code: 'ER', dialCode: '+291' },
  { name: 'Spain', code: 'ES', dialCode: '+34' },
  { name: 'Ethiopia', code: 'ET', dialCode: '+251' },
  { name: 'Finland', code: 'FI', dialCode: '+358' },
  { name: 'Fiji', code: 'FJ', dialCode: '+679' },
  { name: 'Micronesia', code: 'FM', dialCode: '+691' },
  { name: 'Faroe Islands', code: 'FO', dialCode: '+298' },
  { name: 'France', code: 'FR', dialCode: '+33' },
  { name: 'Gabon', code: 'GA', dialCode: '+241' },
  { name: 'United Kingdom', code: 'GB', dialCode: '+44' },
  { name: 'Grenada', code: 'GD', dialCode: '+1-473' },
  { name: 'Georgia', code: 'GE', dialCode: '+995' },
  { name: 'French Guiana', code: 'GF', dialCode: '+594' },
  { name: 'Guernsey', code: 'GG', dialCode: '+44' },
  { name: 'Ghana', code: 'GH', dialCode: '+233' },
  { name: 'Gibraltar', code: 'GI', dialCode: '+350' },
  { name: 'Greenland', code: 'GL', dialCode: '+299' },
  { name: 'Gambia', code: 'GM', dialCode: '+220' },
  { name: 'Guinea', code: 'GN', dialCode: '+224' },
  { name: 'Guadeloupe', code: 'GP', dialCode: '+590' },
  { name: 'Equatorial Guinea', code: 'GQ', dialCode: '+240' },
  { name: 'Greece', code: 'GR', dialCode: '+30' },
  { name: 'Guatemala', code: 'GT', dialCode: '+502' },
  { name: 'Guam', code: 'GU', dialCode: '+1-671' },
  { name: 'Guinea-Bissau', code: 'GW', dialCode: '+245' },
  { name: 'Guyana', code: 'GY', dialCode: '+592' },
  { name: 'Hong Kong', code: 'HK', dialCode: '+852' },
  { name: 'Honduras', code: 'HN', dialCode: '+504' },
  { name: 'Croatia', code: 'HR', dialCode: '+385' },
  { name: 'Haiti', code: 'HT', dialCode: '+509' },
  { name: 'Hungary', code: 'HU', dialCode: '+36' },
  { name: 'Indonesia', code: 'ID', dialCode: '+62' },
  { name: 'Ireland', code: 'IE', dialCode: '+353' },
  { name: 'Israel', code: 'IL', dialCode: '+972' },
  { name: 'Isle of Man', code: 'IM', dialCode: '+44' },
  { name: 'India', code: 'IN', dialCode: '+91' },
  { name: 'Iraq', code: 'IQ', dialCode: '+964' },
  { name: 'Iran', code: 'IR', dialCode: '+98' },
  { name: 'Iceland', code: 'IS', dialCode: '+354' },
  { name: 'Italy', code: 'IT', dialCode: '+39' },
  { name: 'Jersey', code: 'JE', dialCode: '+44' },
  { name: 'Jamaica', code: 'JM', dialCode: '+1-876' },
  { name: 'Jordan', code: 'JO', dialCode: '+962' },
  { name: 'Japan', code: 'JP', dialCode: '+81' },
  { name: 'Kenya', code: 'KE', dialCode: '+254' },
  { name: 'Kyrgyzstan', code: 'KG', dialCode: '+996' },
  { name: 'Cambodia', code: 'KH', dialCode: '+855' },
  { name: 'Kiribati', code: 'KI', dialCode: '+686' },
  { name: 'Comoros', code: 'KM', dialCode: '+269' },
  { name: 'Saint Kitts and Nevis', code: 'KN', dialCode: '+1-869' },
  { name: 'North Korea', code: 'KP', dialCode: '+850' },
  { name: 'South Korea', code: 'KR', dialCode: '+82' },
  { name: 'Kuwait', code: 'KW', dialCode: '+965' },
  { name: 'Cayman Islands', code: 'KY', dialCode: '+1-345' },
  { name: 'Kazakhstan', code: 'KZ', dialCode: '+7' },
  { name: 'Laos', code: 'LA', dialCode: '+856' },
  { name: 'Lebanon', code: 'LB', dialCode: '+961' },
  { name: 'Saint Lucia', code: 'LC', dialCode: '+1-758' },
  { name: 'Liechtenstein', code: 'LI', dialCode: '+423' },
  { name: 'Sri Lanka', code: 'LK', dialCode: '+94' },
  { name: 'Liberia', code: 'LR', dialCode: '+231' },
  { name: 'Lesotho', code: 'LS', dialCode: '+266' },
  { name: 'Lithuania', code: 'LT', dialCode: '+370' },
  { name: 'Luxembourg', code: 'LU', dialCode: '+352' },
  { name: 'Latvia', code: 'LV', dialCode: '+371' },
  { name: 'Libya', code: 'LY', dialCode: '+218' },
  { name: 'Morocco', code: 'MA', dialCode: '+212' },
  { name: 'Monaco', code: 'MC', dialCode: '+377' },
  { name: 'Moldova', code: 'MD', dialCode: '+373' },
  { name: 'Montenegro', code: 'ME', dialCode: '+382' },
  { name: 'Saint Martin', code: 'MF', dialCode: '+590' },
  { name: 'Madagascar', code: 'MG', dialCode: '+261' },
  { name: 'Marshall Islands', code: 'MH', dialCode: '+692' },
  { name: 'North Macedonia', code: 'MK', dialCode: '+389' },
  { name: 'Mali', code: 'ML', dialCode: '+223' },
  { name: 'Myanmar', code: 'MM', dialCode: '+95' },
  { name: 'Mongolia', code: 'MN', dialCode: '+976' },
  { name: 'Macau', code: 'MO', dialCode: '+853' },
  { name: 'Northern Mariana Islands', code: 'MP', dialCode: '+1-670' },
  { name: 'Martinique', code: 'MQ', dialCode: '+596' },
  { name: 'Mauritania', code: 'MR', dialCode: '+222' },
  { name: 'Montserrat', code: 'MS', dialCode: '+1-664' },
  { name: 'Malta', code: 'MT', dialCode: '+356' },
  { name: 'Mauritius', code: 'MU', dialCode: '+230' },
  { name: 'Maldives', code: 'MV', dialCode: '+960' },
  { name: 'Malawi', code: 'MW', dialCode: '+265' },
  { name: 'Mexico', code: 'MX', dialCode: '+52' },
  { name: 'Malaysia', code: 'MY', dialCode: '+60' },
  { name: 'Mozambique', code: 'MZ', dialCode: '+258' },
  { name: 'Namibia', code: 'NA', dialCode: '+264' },
  { name: 'New Caledonia', code: 'NC', dialCode: '+687' },
  { name: 'Niger', code: 'NE', dialCode: '+227' },
  { name: 'Norfolk Island', code: 'NF', dialCode: '+672' },
  { name: 'Nigeria', code: 'NG', dialCode: '+234' },
  { name: 'Nicaragua', code: 'NI', dialCode: '+505' },
  { name: 'Netherlands', code: 'NL', dialCode: '+31' },
  { name: 'Norway', code: 'NO', dialCode: '+47' },
  { name: 'Nepal', code: 'NP', dialCode: '+977' },
  { name: 'Nauru', code: 'NR', dialCode: '+674' },
  { name: 'Niue', code: 'NU', dialCode: '+683' },
  { name: 'New Zealand', code: 'NZ', dialCode: '+64' },
  { name: 'Oman', code: 'OM', dialCode: '+968' },
  { name: 'Panama', code: 'PA', dialCode: '+507' },
  { name: 'Peru', code: 'PE', dialCode: '+51' },
  { name: 'French Polynesia', code: 'PF', dialCode: '+689' },
  { name: 'Papua New Guinea', code: 'PG', dialCode: '+675' },
  { name: 'Philippines', code: 'PH', dialCode: '+63' },
  { name: 'Pakistan', code: 'PK', dialCode: '+92' },
  { name: 'Poland', code: 'PL', dialCode: '+48' },
  { name: 'Saint Pierre and Miquelon', code: 'PM', dialCode: '+508' },
  { name: 'Pitcairn', code: 'PN', dialCode: '+64' },
  { name: 'Puerto Rico', code: 'PR', dialCode: '+1-787' },
  { name: 'Portugal', code: 'PT', dialCode: '+351' },
  { name: 'Palau', code: 'PW', dialCode: '+680' },
  { name: 'Paraguay', code: 'PY', dialCode: '+595' },
  { name: 'Qatar', code: 'QA', dialCode: '+974' },
  { name: 'Reunion', code: 'RE', dialCode: '+262' },
  { name: 'Romania', code: 'RO', dialCode: '+40' },
  { name: 'Serbia', code: 'RS', dialCode: '+381' },
  { name: 'Russia', code: 'RU', dialCode: '+7' },
  { name: 'Rwanda', code: 'RW', dialCode: '+250' },
  { name: 'Saudi Arabia', code: 'SA', dialCode: '+966' },
  { name: 'Solomon Islands', code: 'SB', dialCode: '+677' },
  { name: 'Seychelles', code: 'SC', dialCode: '+248' },
  { name: 'Sudan', code: 'SD', dialCode: '+249' },
  { name: 'Sweden', code: 'SE', dialCode: '+46' },
  { name: 'Singapore', code: 'SG', dialCode: '+65' },
  { name: 'Saint Helena', code: 'SH', dialCode: '+290' },
  { name: 'Slovenia', code: 'SI', dialCode: '+386' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ', dialCode: '+47' },
  { name: 'Slovakia', code: 'SK', dialCode: '+421' },
  { name: 'Sierra Leone', code: 'SL', dialCode: '+232' },
  { name: 'San Marino', code: 'SM', dialCode: '+378' },
  { name: 'Senegal', code: 'SN', dialCode: '+221' },
  { name: 'Somalia', code: 'SO', dialCode: '+252' },
  { name: 'Suriname', code: 'SR', dialCode: '+597' },
  { name: 'South Sudan', code: 'SS', dialCode: '+211' },
  { name: 'Sao Tome and Principe', code: 'ST', dialCode: '+239' },
  { name: 'El Salvador', code: 'SV', dialCode: '+503' },
  { name: 'Sint Maarten', code: 'SX', dialCode: '+1-721' },
  { name: 'Syria', code: 'SY', dialCode: '+963' },
  { name: 'Eswatini', code: 'SZ', dialCode: '+268' },
  { name: 'Turks and Caicos Islands', code: 'TC', dialCode: '+1-649' },
  { name: 'Chad', code: 'TD', dialCode: '+235' },
  { name: 'Togo', code: 'TG', dialCode: '+228' },
  { name: 'Thailand', code: 'TH', dialCode: '+66' },
  { name: 'Tajikistan', code: 'TJ', dialCode: '+992' },
  { name: 'Tokelau', code: 'TK', dialCode: '+690' },
  { name: 'Timor-Leste', code: 'TL', dialCode: '+670' },
  { name: 'Turkmenistan', code: 'TM', dialCode: '+993' },
  { name: 'Tunisia', code: 'TN', dialCode: '+216' },
  { name: 'Tonga', code: 'TO', dialCode: '+676' },
  { name: 'Turkey', code: 'TR', dialCode: '+90' },
  { name: 'Trinidad and Tobago', code: 'TT', dialCode: '+1-868' },
  { name: 'Tuvalu', code: 'TV', dialCode: '+688' },
  { name: 'Taiwan', code: 'TW', dialCode: '+886' },
  { name: 'Tanzania', code: 'TZ', dialCode: '+255' },
  { name: 'Ukraine', code: 'UA', dialCode: '+380' },
  { name: 'Uganda', code: 'UG', dialCode: '+256' },
  { name: 'United States', code: 'US', dialCode: '+1' },
  { name: 'Uruguay', code: 'UY', dialCode: '+598' },
  { name: 'Uzbekistan', code: 'UZ', dialCode: '+998' },
  { name: 'Vatican', code: 'VA', dialCode: '+379' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', dialCode: '+1-784' },
  { name: 'Venezuela', code: 'VE', dialCode: '+58' },
  { name: 'British Virgin Islands', code: 'VG', dialCode: '+1-284' },
  { name: 'U.S. Virgin Islands', code: 'VI', dialCode: '+1-340' },
  { name: 'Vietnam', code: 'VN', dialCode: '+84' },
  { name: 'Vanuatu', code: 'VU', dialCode: '+678' },
  { name: 'Wallis and Futuna', code: 'WF', dialCode: '+681' },
  { name: 'Samoa', code: 'WS', dialCode: '+685' },
  { name: 'Kosovo', code: 'XK', dialCode: '+383' },
  { name: 'Yemen', code: 'YE', dialCode: '+967' },
  { name: 'Mayotte', code: 'YT', dialCode: '+262' },
  { name: 'South Africa', code: 'ZA', dialCode: '+27' },
  { name: 'Zambia', code: 'ZM', dialCode: '+260' },
  { name: 'Zimbabwe', code: 'ZW', dialCode: '+263' },
];

export default countries 
